# Generated by Django 6.0.2 on 2026-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('source', models.CharField(db_comment='The source of the import, e.g. file name or URL.', help_text='Identifier for the data source (e.g. a URL or a file name).', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PARTIAL_SUCCESS', 'Partial Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_comment='Current status of the import process.', default='PENDING', help_text='Current state of the import run. Accepted values: `PENDING`, `IN_PROGRESS`, `PARTIAL_SUCCESS`, `SUCCESS`, `FAILED`.', max_length=20)),
                ('records_total', models.PositiveIntegerField(db_comment='Total number of records processed.', default=0, help_text='Total number of records encountered during the import run.')),
                ('records_imported', models.PositiveIntegerField(db_comment='Number of successfully imported records.', default=0, help_text='Number of records successfully imported.')),
                ('records_failed', models.PositiveIntegerField(db_comment='Number of failed records.', default=0, help_text='Number of records that could not be imported.')),
                ('started_at', models.DateTimeField(blank=True, db_comment='Timestamp when the import started.', help_text='ISO 8601 UTC timestamp at which the import run began.', null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_comment='Timestamp when the import finished.', help_text='ISO 8601 UTC timestamp at which the import run ended. `null` while the run is still in progress. Must not be earlier than `started_at`.', null=True)),
                ('error_message', models.TextField(blank=True, db_comment='Error message if the import failed.', help_text='Human-readable error detail populated when the run fails or encounters problems. `null` when the run completed without error.', null=True)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'db_table': 'import_log',
                'ordering': ['-started_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='importlog_finished_after_or_equal_started')],
            },
        ),
    ]
