# Generated by Django 6.0.2 on 2026-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importlog',
            name='importlog_finished_after_or_equal_started',
        ),
        migrations.AlterField(
            model_name='importlog',
            name='error_message',
            field=models.TextField(blank=True, db_comment='Error message if the import failed', null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_comment='Timestamp when the import finished', null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='records_failed',
            field=models.PositiveIntegerField(db_comment='Number of failed records', default=0),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='records_imported',
            field=models.PositiveIntegerField(db_comment='Number of successfully imported records', default=0),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='records_total',
            field=models.PositiveIntegerField(db_comment='Total number of records processed', default=0),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='source',
            field=models.CharField(help_text='The source of the import, e.g., file name or URL.', max_length=255),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='started_at',
            field=models.DateTimeField(blank=True, db_comment='Timestamp when the import started', null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PARTIAL_SUCCESS', 'Partial Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_comment='Current status of the import process', default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='importlog',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('finished_at__isnull', True), ('finished_at__gt', models.F('started_at')), _connector='OR'), name='importlog_finished_after_started'),
        ),
    ]
