# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ['-started_at'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Import Log', 'verbose_name_plural': 'Import Logs'},
        ),
    ]
