# Generated by Django 6.0.2 on 2026-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_log', '0004_remove_importlog_importlog_finished_after_or_equal_started_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importlog',
            name='importlog_finished_after_started',
        ),
        migrations.AlterField(
            model_name='importlog',
            name='error_message',
            field=models.TextField(blank=True, db_comment='Error message if the import failed.', help_text='Human-readable error detail populated when the run fails or encounters problems. `null` when the run completed without error.', null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_comment='Timestamp when the import finished.', help_text='ISO 8601 UTC timestamp at which the import run ended. `null` while the run is still in progress. Must not be earlier than `started_at`.', null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='records_failed',
            field=models.PositiveIntegerField(db_comment='Number of failed records.', default=0, help_text='Number of records that could not be imported.'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='records_imported',
            field=models.PositiveIntegerField(db_comment='Number of successfully imported records.', default=0, help_text='Number of records successfully imported.'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='records_total',
            field=models.PositiveIntegerField(db_comment='Total number of records processed.', default=0, help_text='Total number of records encountered during the import run.'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='source',
            field=models.CharField(db_comment='The source of the import, e.g. file name or URL.', help_text='Identifier for the data source (e.g. a URL or a file name).', max_length=255),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='started_at',
            field=models.DateTimeField(blank=True, db_comment='Timestamp when the import started.', help_text='ISO 8601 UTC timestamp at which the import run began.', null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PARTIAL_SUCCESS', 'Partial Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_comment='Current status of the import process.', default='PENDING', help_text='Current state of the import run. Accepted values: `PENDING`, `IN_PROGRESS`, `PARTIAL_SUCCESS`, `SUCCESS`, `FAILED`.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='importlog',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='importlog_finished_after_or_equal_started'),
        ),
    ]
