# Generated by Django 6.0.3 on 2026-03-10 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('type', models.CharField(db_comment='Price type / category.', help_text='Internal identifier for the price category (e.g. `full`, `student`).', max_length=50)),
                ('visibility', models.CharField(db_comment='Visibility of the price.', help_text='Controls which audiences see this price (e.g. `public`, `members_only`).', max_length=50)),
                ('membership', models.CharField(blank=True, db_comment='Membership requirement for the price.', default='', help_text='Membership level required to access this price. Empty string means no requirement.', max_length=50)),
                ('minimum', models.PositiveSmallIntegerField(blank=True, db_comment='Minimum allowed amount for variable pricing.', help_text='Lower bound for variable pricing in euro cents (inclusive). Must be set together with `maximum` and `step`, or left null.', null=True)),
                ('maximum', models.PositiveSmallIntegerField(blank=True, db_comment='Maximum allowed amount for variable pricing.', help_text='Upper bound for variable pricing in euro cents (inclusive). Must be set together with `minimum` and `step`, or left null.', null=True)),
                ('step', models.IntegerField(blank=True, db_comment='Step size for variable pricing.', help_text='Increment size in euro cents for variable pricing. Must be ≥ 1. Must be set together with `minimum` and `maximum`, or left null.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.PositiveIntegerField(db_comment='Ordering index for displaying prices.', default=0, help_text='Display order index. Lower values appear first.')),
                ('cineville_box', models.BooleanField(db_comment='Whether this price is for Cineville box.', default=False, help_text='`true` when this price applies to Cineville box holders.')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'price',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('maximum__isnull', True), ('minimum__isnull', True)), ('minimum__lte', models.F('maximum')), _connector='OR'), name='price_min_lte_max')],
            },
        ),
        migrations.CreateModel(
            name='PriceRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('position', models.PositiveIntegerField(db_comment='Rank position used for ordering / priority.', help_text='Rank position used for ordering and priority. Must be unique.')),
                ('sold_out_buffer', models.PositiveIntegerField(db_comment='Extra buffer for sold-out determination.', default=0, help_text='Extra capacity offset used to consider this rank sold out slightly earlier (positive) or later (negative) than actual capacity.')),
            ],
            options={
                'verbose_name': 'Price Rank',
                'verbose_name_plural': 'Price Ranks',
                'db_table': 'price_rank',
                'ordering': ['position', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('position',), name='uniq_price_rank_position')],
            },
        ),
        migrations.CreateModel(
            name='PriceRankTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('description', models.CharField(blank=True, db_comment='Translated description of the price rank.', default='', help_text='Localised human-readable label for this price rank.', max_length=255)),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='pricerank_translations', to='languages.language')),
                ('price_rank', models.ForeignKey(db_comment='FK to PriceRank.', help_text='Price rank this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.pricerank')),
            ],
            options={
                'verbose_name': 'Price Rank Translation',
                'verbose_name_plural': 'Price Rank Translations',
                'db_table': 'price_rank_translation',
                'ordering': ['id'],
                'abstract': False,
                'indexes': [models.Index(fields=['price_rank', 'language'], name='idx_price_rank_lang')],
                'constraints': [models.UniqueConstraint(fields=('price_rank', 'language'), name='unique_price_rank_language')],
            },
        ),
        migrations.CreateModel(
            name='PriceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('description', models.CharField(blank=True, db_comment='Translated description of the price.', default='', help_text='Localised human-readable label for this price (e.g. `Full price`, `Student`).', max_length=255)),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='price_translations', to='languages.language')),
                ('price', models.ForeignKey(db_comment='FK to Price.', help_text='Price this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.price')),
            ],
            options={
                'verbose_name': 'Price Translation',
                'verbose_name_plural': 'Price Translations',
                'db_table': 'price_translation',
                'ordering': ['id'],
                'abstract': False,
                'indexes': [models.Index(fields=['price', 'language'], name='idx_price_lang')],
                'constraints': [models.UniqueConstraint(fields=('price', 'language'), name='unique_price_language')],
            },
        ),
    ]
