# Generated by Django 6.0.5 on 2026-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerank',
            name='sold_out_buffer',
            field=models.PositiveIntegerField(db_comment='Extra buffer for sold-out determination.', default=0, help_text='Positive capacity offset used to consider this rank sold out before actual capacity reaches zero.'),
        ),
    ]
