# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['sort_order', 'id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='pricerank',
            options={'ordering': ['position', 'id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Price Rank', 'verbose_name_plural': 'Price Ranks'},
        ),
        migrations.AlterModelOptions(
            name='priceranktranslation',
            options={'ordering': ['id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Price Rank Translation', 'verbose_name_plural': 'Price Rank Translations'},
        ),
        migrations.AlterModelOptions(
            name='pricetranslation',
            options={'ordering': ['id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Price Translation', 'verbose_name_plural': 'Price Translations'},
        ),
    ]
