# Generated by Django 6.0.2 on 2026-03-04 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_alter_language_code_alter_language_is_active_and_more'),
        ('pricing', '0003_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['sort_order'], 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='priceranktranslation',
            options={'verbose_name': 'Price Rank Translation', 'verbose_name_plural': 'Price Rank Translations'},
        ),
        migrations.AlterModelOptions(
            name='pricetranslation',
            options={'verbose_name': 'Price Translation', 'verbose_name_plural': 'Price Translations'},
        ),
        migrations.AlterField(
            model_name='price',
            name='cineville_box',
            field=models.BooleanField(db_comment='Whether this price is for Cineville box.', default=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='maximum',
            field=models.PositiveSmallIntegerField(blank=True, db_comment='Maximum allowed amount (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='membership',
            field=models.CharField(blank=True, db_comment='Membership requirement.', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='price',
            name='minimum',
            field=models.PositiveSmallIntegerField(blank=True, db_comment='Minimum allowed amount (if applicable).', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='Ordering index for displaying prices.', default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='step',
            field=models.IntegerField(blank=True, db_comment='Step size for variable pricing (if applicable).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(db_comment='Price type/category.', max_length=50),
        ),
        migrations.AlterField(
            model_name='price',
            name='visibility',
            field=models.CharField(db_comment='Visibility of the price.', max_length=50),
        ),
        migrations.AlterField(
            model_name='pricerank',
            name='position',
            field=models.PositiveIntegerField(db_comment='Rank position used for ordering/priority.'),
        ),
        migrations.AlterField(
            model_name='pricerank',
            name='sold_out_buffer',
            field=models.PositiveIntegerField(db_comment='Extra buffer used to consider rank sold out earlier/later.', default=0),
        ),
        migrations.AlterField(
            model_name='priceranktranslation',
            name='description',
            field=models.CharField(blank=True, db_comment='Description of the price rank translation.', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='priceranktranslation',
            name='language',
            field=models.ForeignKey(db_comment='The language that corresponds to the translation of the price rank.', on_delete=django.db.models.deletion.CASCADE, related_name='pricerank_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='priceranktranslation',
            name='price_rank',
            field=models.ForeignKey(db_comment='The price rank that this is a translation of.', on_delete=django.db.models.deletion.CASCADE, to='pricing.pricerank'),
        ),
        migrations.AlterField(
            model_name='pricetranslation',
            name='description',
            field=models.CharField(blank=True, db_comment='Description of the price translation.', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricetranslation',
            name='language',
            field=models.ForeignKey(db_comment='The language that corresponds to the translation.', on_delete=django.db.models.deletion.CASCADE, related_name='price_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='pricetranslation',
            name='price',
            field=models.ForeignKey(db_comment='The price that this is a translation of.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.price'),
        ),
    ]
