# Generated by Django 6.0.2 on 2026-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='pricerank',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='priceranktranslation',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='pricetranslation',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
    ]
