# Generated by Django 6.0.2 on 2026-03-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_price_external_id_pricerank_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='price_min_max_both_null_or_both_set',
        ),
    ]
