# Generated by Django 6.0.3 on 2026-03-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('pricing', '0001_initial'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('starts_at', models.DateTimeField(blank=True, db_comment='The time at which the event starts.', help_text='ISO 8601 UTC datetime at which the event begins.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_comment='The time at which the event ends.', help_text='ISO 8601 UTC datetime at which the event ends. Must be later or equal to `starts_at`.', null=True)),
                ('hall', models.ForeignKey(blank=True, db_comment='The hall which the event is organized in.', help_text='Hall in which the event takes place. `null` for online or location-independent events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.hall')),
                ('production', models.ForeignKey(db_comment='The production that the event is organized for.', help_text='Production this event is a performance of.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='productions.production')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
                'ordering': ['starts_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('amount', models.DecimalField(db_comment='The price amount.', decimal_places=2, help_text='Ticket price in euro (e.g. `18.00`).', max_digits=10)),
                ('available', models.PositiveIntegerField(db_comment='The amount of event tickets available for this specific price.', help_text='Number of tickets available at this price rank for the event.')),
                ('event', models.ForeignKey(db_comment='The event which the price belongs to.', help_text='Event this price entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='events.event')),
                ('price', models.ForeignKey(blank=True, db_comment='FK to Price.', help_text='Price category for this event price entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prices', to='pricing.price')),
                ('price_rank', models.ForeignKey(blank=True, db_comment='The rank corresponding to the price.', help_text='Price rank availability tier. `null` when the rank has been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prices', to='pricing.pricerank')),
            ],
            options={
                'verbose_name': 'Event Price',
                'verbose_name_plural': 'Event Prices',
                'db_table': 'event_price',
                'ordering': ['price_rank__position', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at')), ('starts_at__isnull', True), ('ends_at__isnull', True), _connector='OR'), name='event_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='eventprice',
            index=models.Index(fields=['event'], name='idx_event_price_event'),
        ),
        migrations.AddIndex(
            model_name='eventprice',
            index=models.Index(fields=['event', 'price_rank', 'price'], name='idx_event_rank_price'),
        ),
        migrations.AddConstraint(
            model_name='eventprice',
            constraint=models.UniqueConstraint(fields=('event', 'price_rank', 'price'), name='uniq_event_rank_price'),
        ),
    ]
