# Generated by Django 6.0.2 on 2026-03-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        ('productions', '0003_alter_production_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(blank=True, db_comment='The hall which the event is organized in.', help_text='Hall in which the event takes place. `null` for online or location-independent events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.hall'),
        ),
        migrations.AddField(
            model_name='event',
            name='production',
            field=models.ForeignKey(db_comment='The production that the event is organized for.', help_text='Production this event is a performance of.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='productions.production'),
        ),
        migrations.AddField(
            model_name='eventprice',
            name='event',
            field=models.ForeignKey(db_comment='The event which the price belongs to.', help_text='Event this price entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='events.event'),
        ),
    ]
