# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starts_at'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventprice',
            options={'ordering': ['price_rank__position', 'id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Event Price', 'verbose_name_plural': 'Event Prices'},
        ),
    ]
