# Generated by Django 6.0.2 on 2026-03-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprice',
            name='price_rank',
            field=models.ForeignKey(blank=True, db_comment='The rank corresponding to the price.', help_text='Price rank availability tier. `null` when the rank has been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prices', to='pricing.pricerank'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='eventprice',
            index=models.Index(fields=['event'], name='idx_event_price_event'),
        ),
        migrations.AddIndex(
            model_name='eventprice',
            index=models.Index(fields=['event', 'price_rank'], name='idx_event_price_event_rank'),
        ),
        migrations.AddConstraint(
            model_name='eventprice',
            constraint=models.UniqueConstraint(fields=('event', 'price_rank'), name='uniq_event_price_rank'),
        ),
    ]
