# Generated by Django 6.0.2 on 2026-03-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventprice_options_and_more'),
        ('locations', '0005_alter_hall_options_alter_halltranslation_options_and_more'),
        ('pricing', '0005_alter_price_options_and_more'),
        ('productions', '0007_alter_production_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventprice',
            options={'ordering': ['price_rank__position', 'id'], 'verbose_name': 'Event Price', 'verbose_name_plural': 'Event Prices'},
        ),
        migrations.RenameIndex(
            model_name='eventprice',
            new_name='idx_event_price_event',
            old_name='event_price_event_i_15e551_idx',
        ),
        migrations.RenameIndex(
            model_name='eventprice',
            new_name='idx_event_price_event_rank',
            old_name='event_price_event_i_4cf9df_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_comment='The time at which the event ends.', help_text='ISO 8601 UTC datetime at which the event ends. Must be strictly later than `starts_at`.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(blank=True, db_comment='The hall which the event is organized in.', help_text='Hall in which the event takes place. `null` for online or location-independent events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.hall'),
        ),
        migrations.AlterField(
            model_name='event',
            name='production',
            field=models.ForeignKey(db_comment='The production that the event is organized for.', help_text='Production this event is a performance of.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='productions.production'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_comment='The time at which the event starts.', help_text='ISO 8601 UTC datetime at which the event begins.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticketing_url',
            field=models.URLField(blank=True, db_comment='The URL leading to the ticket reservations.', help_text='Public URL where tickets for this event can be purchased. Empty string when not applicable.'),
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='amount',
            field=models.DecimalField(db_comment='The price amount.', decimal_places=2, help_text='Ticket price in euro (e.g. `18.00`).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='available',
            field=models.PositiveIntegerField(db_comment='The amount of event tickets available for this specific price.', help_text='Number of tickets available at this price rank for the event.'),
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='event',
            field=models.ForeignKey(db_comment='The event which the price belongs to.', help_text='Event this price entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='price_rank',
            field=models.ForeignKey(blank=True, db_comment='The rank corresponding to the price.', help_text='Price rank availability tier. `null` when the rank has been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prices', to='pricing.pricerank'),
        ),
    ]
