# Generated by Django 6.0.2 on 2026-03-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_external_id_eventprice_external_id'),
        ('locations', '0007_alter_hall_space_alter_location_city_and_more'),
        ('pricing', '0007_remove_price_price_min_max_both_null_or_both_set'),
        ('productions', '0008_production_external_id_productiongenre_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_ends_after_starts',
        ),
        migrations.RemoveConstraint(
            model_name='eventprice',
            name='uniq_event_price_rank',
        ),
        migrations.RemoveIndex(
            model_name='eventprice',
            name='idx_event_price_event_rank',
        ),
        migrations.AddField(
            model_name='eventprice',
            name='price',
            field=models.ForeignKey(blank=True, db_comment='FK to Price.', help_text='Price category for this event price entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_prices', to='pricing.price'),
        ),
        migrations.AddIndex(
            model_name='eventprice',
            index=models.Index(fields=['event', 'price_rank', 'price'], name='idx_event_rank_price'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at')), ('starts_at__isnull', True), ('ends_at__isnull', True), _connector='OR'), name='event_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='eventprice',
            constraint=models.UniqueConstraint(fields=('event', 'price_rank', 'price'), name='uniq_event_rank_price'),
        ),
    ]
