# Generated by Django 6.0.3 on 2026-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_event_ends_after_starts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_comment='The time at which the event ends.', help_text='ISO 8601 UTC datetime at which the event ends. Must be later or equal to `starts_at`.', null=True),
        ),
    ]
