# Generated by Django 6.0.2 on 2026-03-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('url', models.URLField(blank=True, db_comment='The URL of the tag, if it exists.', help_text='Public URL of the tag in the originating system. Empty string when not applicable.')),
                ('source', models.CharField(blank=True, db_comment='Source of the tag (e.g. system, external API).', help_text='Identifier of the system that created this tag (e.g. `uitdatabank`, `system`).', max_length=255)),
                ('source_type', models.CharField(blank=True, db_comment='Type of the source.', help_text='Sub-classification of the source (e.g. `theme`, `targetAudience`).', max_length=100)),
                ('is_external', models.BooleanField(db_comment='Whether this tag originates from an external system.', default=False, help_text='`true` when this tag was imported from an external system.')),
                ('is_enabled', models.BooleanField(db_comment='Whether the tag is enabled.', default=True, help_text='`false` to soft-disable the tag without deleting it.')),
                ('type', models.CharField(blank=True, db_comment='Type/category of the tag.', help_text='Internal category of the tag used for grouping (e.g. `theme`, `audience`).', max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='The name of the tag in the specified language.', help_text='Localised display name of the tag (e.g. `Contemporary`, `Family friendly`).', max_length=255)),
                ('short_description', models.TextField(blank=True, db_comment='Short description of the tag.', help_text='Optional short description of the tag in this language.', null=True)),
                ('url_title', models.CharField(blank=True, db_comment='URL title in the specified language.', help_text='URL-safe title of the tag in this language (e.g. `contemporary`, `family-friendly`).', max_length=255)),
                ('language', models.ForeignKey(db_comment='The language of the translation.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='tag_translations', to='languages.language')),
                ('tag', models.ForeignKey(db_comment='The tag that this translation belongs to.', help_text='Tag this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Tag Translation',
                'verbose_name_plural': 'Tag Translations',
                'db_table': 'tag_translation',
                'ordering': ['language__code'],
                'abstract': False,
                'indexes': [models.Index(fields=['tag', 'language'], name='idx_tag_lang')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'language'), name='unique_tag_language')],
            },
        ),
    ]
