# Generated by Django 6.0.2 on 2026-02-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
