# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_image_tagtranslation_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagtranslation',
            options={'ordering': ['language__code'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Tag Translation', 'verbose_name_plural': 'Tag Translations'},
        ),
    ]
