# Generated by Django 6.0.4 on 2026-05-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('tags', '0003_tag_image_tagtranslation_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.AddField(
            model_name='tag',
            name='media_gallery',
            field=models.ForeignKey(blank=True, db_comment='Media gallery associated with this tag.', help_text='Media gallery associated with this tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='media_library.mediagallery'),
        ),
    ]
