# Generated by Django 6.0.2 on 2026-03-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_alter_language_code_alter_language_is_active_and_more'),
        ('tags', '0005_alter_tag_options_alter_tagtranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagtranslation',
            options={'verbose_name': 'Tag Translation', 'verbose_name_plural': 'Tag Translations'},
        ),
        migrations.RemoveIndex(
            model_name='tagtranslation',
            name='idx_tag_lang',
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_enabled',
            field=models.BooleanField(db_comment='Whether the tag is enabled', default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_external',
            field=models.BooleanField(db_comment='Whether this tag originates from an external system', default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source',
            field=models.CharField(blank=True, db_comment='Source of the tag (e.g. system, external API)', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_type',
            field=models.CharField(blank=True, db_comment='Type of the source', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, db_comment='Type/category of the tag', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.URLField(blank=True, db_comment='The URL of the tag, if it exists.'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='language',
            field=models.ForeignKey(db_comment='The language of the translation.', on_delete=django.db.models.deletion.CASCADE, related_name='tag_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='name',
            field=models.CharField(db_comment='The name of the tag in the specified language.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='short_description',
            field=models.TextField(blank=True, db_comment='Short description of the tag', null=True),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='tag',
            field=models.ForeignKey(db_comment='The tag that this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='url_title',
            field=models.CharField(blank=True, db_comment='URL title in the specified language', max_length=255),
        ),
    ]
