# Generated by Django 6.0.2 on 2026-03-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_alter_language_code_alter_language_is_active_and_more'),
        ('tags', '0006_alter_tag_options_alter_tagtranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagtranslation',
            options={'ordering': ['language__code'], 'verbose_name': 'Tag Translation', 'verbose_name_plural': 'Tag Translations'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_enabled',
            field=models.BooleanField(db_comment='Whether the tag is enabled.', default=True, help_text='`false` to soft-disable the tag without deleting it.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_external',
            field=models.BooleanField(db_comment='Whether this tag originates from an external system.', default=False, help_text='`true` when this tag was imported from an external system.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source',
            field=models.CharField(blank=True, db_comment='Source of the tag (e.g. system, external API).', help_text='Identifier of the system that created this tag (e.g. `uitdatabank`, `system`).', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='source_type',
            field=models.CharField(blank=True, db_comment='Type of the source.', help_text='Sub-classification of the source (e.g. `theme`, `targetAudience`).', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, db_comment='Type/category of the tag.', help_text='Internal category of the tag used for grouping (e.g. `theme`, `audience`).', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.URLField(blank=True, db_comment='The URL of the tag, if it exists.', help_text='Public URL of the tag in the originating system. Empty string when not applicable.'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='language',
            field=models.ForeignKey(db_comment='The language of the translation.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='tag_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='name',
            field=models.CharField(db_comment='The name of the tag in the specified language.', help_text='Localised display name of the tag (e.g. `Contemporary`, `Family friendly`).', max_length=255),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='short_description',
            field=models.TextField(blank=True, db_comment='Short description of the tag.', help_text='Optional short description of the tag in this language.', null=True),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='tag',
            field=models.ForeignKey(db_comment='The tag that this translation belongs to.', help_text='Tag this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='url_title',
            field=models.CharField(blank=True, db_comment='URL title in the specified language.', help_text='URL-safe title of the tag in this language (e.g. `contemporary`, `family-friendly`).', max_length=255),
        ),
        migrations.AddIndex(
            model_name='tagtranslation',
            index=models.Index(fields=['tag', 'language'], name='idx_tag_lang'),
        ),
    ]
