# Generated by Django 5.2.11 on 2026-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
