# Generated by Django 6.0.3 on 2026-04-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0002_rename_original_name_to_filename'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='media_item',
            field=models.ForeignKey(blank=True, db_comment='FK to MediaItem.', help_text='Optional MediaItem linked to this uploaded file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='media_library.mediaitem'),
        ),
    ]
