# Generated by Django 5.2.11 on 2026-04-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0002_remove_mediafile_uploaded_by_mediafile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
