# Generated by Django 6.0.3 on 2026-04-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0003_mediafile_media_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='media_item',
        ),
    ]
