# Generated by Django 5.2.11 on 2026-04-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('media_files', '0003_alter_mediafile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media file', 'verbose_name_plural': 'Media files'},
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='description',
        ),
        migrations.AlterModelTable(
            name='mediafile',
            table='media_file',
        ),
        migrations.CreateModel(
            name='MediaFileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('description', models.CharField(blank=True, db_comment='Description of the media file in the specified language.', help_text='Localised description of the media file.', max_length=200)),
                ('language', models.ForeignKey(db_comment='The language of the translation.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='media_file_translations', to='languages.language')),
                ('media_file', models.ForeignKey(db_comment='The media file that this translation belongs to.', help_text='Media file this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='media_files.mediafile')),
            ],
            options={
                'verbose_name': 'Media file translation',
                'verbose_name_plural': 'Media file translations',
                'db_table': 'media_file_translation',
                'ordering': ['language__code'],
                'abstract': False,
                'indexes': [models.Index(fields=['media_file', 'language'], name='idx_media_file_lang')],
                'constraints': [models.UniqueConstraint(fields=('media_file', 'language'), name='unique_media_file_language')],
            },
        ),
    ]
