# Generated by Django 5.2.11 on 2026-04-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0004_alter_mediafile_options_remove_mediafile_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media file', 'verbose_name_plural': 'Media files'},
        ),
        migrations.AlterModelOptions(
            name='mediafiletranslation',
            options={'ordering': ['language__code'], 'verbose_name': 'Media file translation', 'verbose_name_plural': 'Media file translations'},
        ),
    ]
