# Generated by Django 5.2.11 on 2026-04-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_alter_mediafile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterModelOptions(
            name='mediafiletranslation',
            options={'ordering': ['language__code'], 'verbose_name': 'Media File Translation', 'verbose_name_plural': 'Media File Translations'},
        ),
    ]
