# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0006_alter_mediafile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterModelOptions(
            name='mediafiletranslation',
            options={'ordering': ['language__code'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Media File Translation', 'verbose_name_plural': 'Media File Translations'},
        ),
    ]
