# Generated by Django 6.0.3 on 2026-04-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('slug', models.SlugField(db_comment='SEO-friendly slug for the blog post.', help_text="URL-friendly identifier for this blog post (e.g., 'i-love-techno-2024').", max_length=255, unique=True)),
                ('published_at', models.DateTimeField(blank=True, db_comment='Publication date and time.', help_text='Publication timestamp. If null, the post is considered a draft.', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image for this blog post.', null=True, upload_to='blog_covers/')),
                ('productions', models.ManyToManyField(blank=True, help_text='Productions linked to this blog post.', related_name='blogs', to='productions.production')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog',
                'ordering': ['-published_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('title', models.CharField(db_comment='Translated title.', help_text='Localized title of the blog post.', max_length=255)),
                ('body', models.TextField(db_comment='Translated body content.', help_text='Localized body content (supports HTML or Markdown).')),
                ('excerpt', models.TextField(blank=True, db_comment='Translated excerpt.', help_text='Optional short excerpt or summary of the post.', null=True)),
                ('blog', models.ForeignKey(db_comment='FK to Blog.', help_text='Blog post this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blogs.blog')),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_translations', to='languages.language')),
            ],
            options={
                'verbose_name': 'Blog Translation',
                'verbose_name_plural': 'Blog Translations',
                'db_table': 'blog_translation',
                'ordering': ['id'],
                'abstract': False,
                'unique_together': {('blog', 'language')},
            },
        ),
    ]
