# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_at', '-id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='blogtranslation',
            options={'ordering': ['id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Blog Translation', 'verbose_name_plural': 'Blog Translations'},
        ),
    ]
