# Generated by Django 6.0.3 on 2026-04-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='productions',
            field=models.ManyToManyField(blank=True, db_comment='M2M relationship to Production.', help_text='Productions linked to this blog post.', related_name='blogs', to='productions.production'),
        ),
    ]
