# Generated by Django 6.0.3 on 2026-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_productions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for this blog post.', null=True, upload_to='blog_covers/'),
        ),
    ]
