# Generated by Django 6.0.3 on 2026-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_cover_image'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='productions',
            field=models.ManyToManyField(blank=True, help_text='Productions linked to this blog post.', related_name='blogs', to='productions.production'),
        ),
    ]
