# Generated by Django 6.0.3 on 2026-04-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_productions'),
        ('media_files', '0004_remove_mediafile_media_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_image_media',
            field=models.ForeignKey(blank=True, help_text='Reference an existing media file as cover image instead of uploading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs_as_cover', to='media_files.mediafile'),
        ),
    ]
