# Generated by Django 6.0.3 on 2026-04-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_cover_image_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover_image_media',
        ),
    ]
