# Generated by Django 6.0.3 on 2026-03-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(blank=True, db_comment='Name of the media gallery.', help_text='Human-readable name of the gallery.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Media Gallery',
                'verbose_name_plural': 'Media Galleries',
                'db_table': 'media_gallery',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('type', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], db_comment='Type of media item.', help_text='Media type: `foto`, `video`, `audio`, or `other`.', max_length=20)),
                ('format', models.CharField(blank=True, db_comment='Format / extension of the media item.', default='', help_text='File format / extension (e.g. `jpg`, `mp4`, `mp3`).', max_length=50)),
                ('original_filename', models.CharField(blank=True, db_comment='Original filename of the media item.', default='', help_text='Original filename as uploaded.', max_length=255)),
                ('position', models.PositiveIntegerField(db_comment='Position of the media item within the gallery.', default=0, help_text='Display order within the gallery. Lower values appear first.')),
                ('width', models.PositiveIntegerField(blank=True, db_comment='Width of the media item in pixels.', help_text='Width in pixels. Applies to images and videos only.', null=True)),
                ('height', models.PositiveIntegerField(blank=True, db_comment='Height of the media item in pixels.', help_text='Height in pixels. Applies to images and videos only.', null=True)),
                ('gallery', models.ForeignKey(blank=True, db_comment='FK to MediaGallery.', help_text='Parent gallery this item belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='media_library.mediagallery')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'db_table': 'media_item',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaItemCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='Name / variant of the crop.', help_text='Crop variant identifier (e.g. `thumbnail`, `banner`, `square`).', max_length=100)),
                ('url', models.URLField(db_comment='URL of the cropped media item.', help_text='Publicly accessible URL of the cropped asset.')),
                ('media_item', models.ForeignKey(db_comment='FK to MediaItem.', help_text='Media item this crop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='media_library.mediaitem')),
            ],
            options={
                'verbose_name': 'Media Item Crop',
                'verbose_name_plural': 'Media Item Crops',
                'db_table': 'media_item_crop',
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('media_item', 'name'), name='unique_crop_name_per_media_item')],
            },
        ),
        migrations.CreateModel(
            name='MediaItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('title', models.CharField(blank=True, db_comment='Translated title of the media item.', default='', help_text='Localised display title of the media item.', max_length=2000)),
                ('description', models.TextField(blank=True, db_comment='Translated description of the media item.', default='', help_text='Localised extended description of the media item.')),
                ('credits', models.CharField(blank=True, db_comment='Translated credits for the media item.', default='', help_text='Localised attribution or credits for the media item.', max_length=300)),
                ('link', models.CharField(blank=True, db_comment='Translated external link for the media item.', help_text='Localised external URL related to the media item.', max_length=255)),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='media_item_translations', to='languages.language')),
                ('media_item', models.ForeignKey(db_comment='FK to MediaItem.', help_text='Media item this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='media_library.mediaitem')),
            ],
            options={
                'verbose_name': 'Media Item Translation',
                'verbose_name_plural': 'Media Item Translations',
                'db_table': 'media_item_translation',
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('media_item', 'language'), name='unique_media_language')],
            },
        ),
    ]
