# Generated by Django 6.0.3 on 2026-03-21 12:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_gallery_item_links(apps, schema_editor):
    MediaItem = apps.get_model('media_library', 'MediaItem')
    MediaGalleryItem = apps.get_model('media_library', 'MediaGalleryItem')

    batch_size = 1000
    rows = []
    queryset = MediaItem.objects.exclude(gallery_id__isnull=True).only('gallery_id', 'id', 'position')
    for item in queryset.iterator(chunk_size=batch_size):
        rows.append(
            MediaGalleryItem(
                gallery_id=item.gallery_id,
                media_item_id=item.id,
                position=item.position or 0,
            )
        )

        if len(rows) >= batch_size:
            MediaGalleryItem.objects.bulk_create(rows, batch_size=batch_size, ignore_conflicts=True)
            rows.clear()

    if rows:
        MediaGalleryItem.objects.bulk_create(rows, batch_size=batch_size, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_comment='Position of the media item within the gallery.', default=0, help_text='Display order of the media item within the gallery.')),
                ('gallery', models.ForeignKey(db_comment='FK to MediaGallery.', help_text='Gallery this media item is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery_items', to='media_library.mediagallery')),
                ('media_item', models.ForeignKey(db_comment='FK to MediaItem.', help_text='Media item linked to the gallery.', on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery_links', to='media_library.mediaitem')),
            ],
            options={
                'verbose_name': 'Media Gallery Item',
                'verbose_name_plural': 'Media Gallery Items',
                'db_table': 'media_gallery_item',
                'ordering': ['gallery_id', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Media items linked to this gallery through MediaGalleryItem.', related_name='galleries', through='media_library.MediaGalleryItem', to='media_library.mediaitem'),
        ),
        migrations.AddConstraint(
            model_name='mediagalleryitem',
            constraint=models.UniqueConstraint(fields=('gallery', 'media_item'), name='unique_media_item_per_gallery'),
        ),
        migrations.RunPython(backfill_gallery_item_links, noop_reverse),
    ]
