# Generated by Django 6.0.3 on 2026-03-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitemcrop',
            name='url',
        ),
    ]
