# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'ordering': ['name'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Media Gallery', 'verbose_name_plural': 'Media Galleries'},
        ),
        migrations.AlterModelOptions(
            name='mediagalleryitem',
            options={'ordering': ['gallery_id', 'position', 'id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Media Gallery Item', 'verbose_name_plural': 'Media Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['position'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Media Item', 'verbose_name_plural': 'Media Items'},
        ),
        migrations.AlterModelOptions(
            name='mediaitemcrop',
            options={'ordering': ['name'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Media Item Crop', 'verbose_name_plural': 'Media Item Crops'},
        ),
        migrations.AlterModelOptions(
            name='mediaitemtranslation',
            options={'ordering': ['id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Media Item Translation', 'verbose_name_plural': 'Media Item Translations'},
        ),
    ]
