# Generated by Django 6.0.2 on 2026-03-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_language_code_alter_language_is_active_and_more'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'verbose_name': 'Media Gallery', 'verbose_name_plural': 'Media Galleries'},
        ),
        migrations.AlterModelOptions(
            name='mediaitemcrop',
            options={'verbose_name': 'Media Item Crop', 'verbose_name_plural': 'Media Item Crops'},
        ),
        migrations.AlterModelOptions(
            name='mediaitemtranslation',
            options={'verbose_name': 'Media Item Translation', 'verbose_name_plural': 'Media Item Translations'},
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='name',
            field=models.CharField(db_comment='Name of the media gallery.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='format',
            field=models.CharField(blank=True, db_comment='Format of the media item (e.g., jpg, mp4).', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='gallery',
            field=models.ForeignKey(db_comment='The media gallery this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='media_library.mediagallery'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='height',
            field=models.PositiveIntegerField(blank=True, db_comment='Height of the media item in pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='original_filename',
            field=models.CharField(blank=True, db_comment='Original filename of the media item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='position',
            field=models.PositiveIntegerField(db_comment='Position of the media item within the gallery.', default=0),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], db_comment='Type of media item.', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='width',
            field=models.PositiveIntegerField(blank=True, db_comment='Width of the media item in pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='media_item',
            field=models.ForeignKey(db_comment='The media item this crop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='media_library.mediaitem'),
        ),
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='name',
            field=models.CharField(db_comment='Name of the crop (e.g., thumbnail, banner).', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='url',
            field=models.URLField(db_comment='URL of the cropped media item.'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='credits',
            field=models.CharField(blank=True, db_comment='Credits for the media item in the specified language.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='description',
            field=models.TextField(blank=True, db_comment='Description of the media item in the specified language.'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='language',
            field=models.ForeignKey(db_comment='Language of the translation.', on_delete=django.db.models.deletion.CASCADE, related_name='media_item_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='link',
            field=models.URLField(blank=True, db_comment='External link related to the media item in the specified language.'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='media_item',
            field=models.ForeignKey(db_comment='The media item this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='media_library.mediaitem'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='title',
            field=models.CharField(blank=True, db_comment='Title of the media item in the specified language.', max_length=255),
        ),
    ]
