# Generated by Django 6.0.3 on 2026-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediagalleryitem_mediagallery_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagalleryitem',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
    ]
