# Generated by Django 6.0.3 on 2026-03-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_remove_mediaitemcrop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitemcrop',
            name='image',
            field=models.ImageField(db_comment='Local path to the downloaded crop image.', default='', help_text='Downloaded crop image stored locally.', upload_to='media_crops/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='name',
            field=models.CharField(db_comment='Name / variant of the crop.', help_text='Crop variant identifier (e.g. `hd_ready`, `FE3_header`).', max_length=100),
        ),
    ]
