# Generated by Django 6.0.3 on 2026-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_mediaitemcrop_image_alter_mediaitemcrop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='image',
            field=models.ImageField(db_comment='Local path to the downloaded crop image.', help_text='Downloaded crop image stored locally.', upload_to='media_crops/%Y/%m/'),
        ),
    ]
