# Generated by Django 6.0.2 on 2026-03-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_alter_language_code_alter_language_is_active_and_more'),
        ('media_library', '0004_alter_mediagallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'ordering': ['name'], 'verbose_name': 'Media Gallery', 'verbose_name_plural': 'Media Galleries'},
        ),
        migrations.AlterModelOptions(
            name='mediaitemcrop',
            options={'ordering': ['name'], 'verbose_name': 'Media Item Crop', 'verbose_name_plural': 'Media Item Crops'},
        ),
        migrations.AlterModelOptions(
            name='mediaitemtranslation',
            options={'ordering': ['id'], 'verbose_name': 'Media Item Translation', 'verbose_name_plural': 'Media Item Translations'},
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='name',
            field=models.CharField(db_comment='Name of the media gallery.', help_text='Human-readable name of the gallery.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='format',
            field=models.CharField(blank=True, db_comment='Format / extension of the media item.', default='', help_text='File format / extension (e.g. `jpg`, `mp4`, `mp3`).', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='gallery',
            field=models.ForeignKey(db_comment='FK to MediaGallery.', help_text='Parent gallery this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='media_library.mediagallery'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='height',
            field=models.PositiveIntegerField(blank=True, db_comment='Height of the media item in pixels.', help_text='Height in pixels. Applies to images and videos only.', null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='original_filename',
            field=models.CharField(blank=True, db_comment='Original filename of the media item.', default='', help_text='Original filename as uploaded.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='position',
            field=models.PositiveIntegerField(db_comment='Position of the media item within the gallery.', default=0, help_text='Display order within the gallery. Lower values appear first.'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], db_comment='Type of media item.', help_text='Media type: `image`, `video`, or `audio`.', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='width',
            field=models.PositiveIntegerField(blank=True, db_comment='Width of the media item in pixels.', help_text='Width in pixels. Applies to images and videos only.', null=True),
        ),
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='media_item',
            field=models.ForeignKey(db_comment='FK to MediaItem.', help_text='Media item this crop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='media_library.mediaitem'),
        ),
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='name',
            field=models.CharField(db_comment='Name / variant of the crop.', help_text='Crop variant identifier (e.g. `thumbnail`, `banner`, `square`).', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaitemcrop',
            name='url',
            field=models.URLField(db_comment='URL of the cropped media item.', help_text='Publicly accessible URL of the cropped asset.'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='credits',
            field=models.CharField(blank=True, db_comment='Translated credits for the media item.', default='', help_text='Localised attribution or credits for the media item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='description',
            field=models.TextField(blank=True, db_comment='Translated description of the media item.', default='', help_text='Localised extended description of the media item.'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='language',
            field=models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='media_item_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='link',
            field=models.URLField(blank=True, db_comment='Translated external link for the media item.', default='', help_text='Localised external URL related to the media item.'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='media_item',
            field=models.ForeignKey(db_comment='FK to MediaItem.', help_text='Media item this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='media_library.mediaitem'),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='title',
            field=models.CharField(blank=True, db_comment='Translated title of the media item.', default='', help_text='Localised display title of the media item.', max_length=255),
        ),
    ]
