# Generated by Django 6.0.2 on 2026-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0005_alter_mediagallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagallery',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='mediaitemcrop',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='mediaitemtranslation',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
    ]
