# Generated by Django 6.0.2 on 2026-03-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0006_mediagallery_external_id_mediaitem_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagallery',
            name='name',
            field=models.CharField(blank=True, db_comment='Name of the media gallery.', help_text='Human-readable name of the gallery.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='gallery',
            field=models.ForeignKey(blank=True, db_comment='FK to MediaGallery.', help_text='Parent gallery this item belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='media_library.mediagallery'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], db_comment='Type of media item.', help_text='Media type: `foto`, `video`, `audio`, or `other`.', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='credits',
            field=models.CharField(blank=True, db_comment='Translated credits for the media item.', default='', help_text='Localised attribution or credits for the media item.', max_length=300),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='link',
            field=models.CharField(blank=True, db_comment='Translated external link for the media item.', help_text='Localised external URL related to the media item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaitemtranslation',
            name='title',
            field=models.CharField(blank=True, db_comment='Translated title of the media item.', default='', help_text='Localised display title of the media item.', max_length=2000),
        ),
    ]
