# Generated by Django 6.0.2 on 2026-03-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('languages', '0001_initial'),
        ('media_library', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UitDatabaseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='The name of the theme.', help_text='Human-readable name of the UIT Database theme (e.g. `Theater`, `Muziek`).', max_length=200)),
            ],
            options={
                'verbose_name': 'UIT Database Theme',
                'verbose_name_plural': 'UIT Database Themes',
                'db_table': 'uit_database_theme',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UitDatabaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='The name of the type.', help_text='Human-readable name of the UIT Database type (e.g. `Voorstelling`, `Concert`).', max_length=200)),
            ],
            options={
                'verbose_name': 'UIT Database Type',
                'verbose_name_plural': 'UIT Database Types',
                'db_table': 'uit_database_type',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('attendance_mode', models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], db_comment='The attendance mode of the production.', help_text='How the audience attends the production. Accepted values: `offline`, `online`.', max_length=20)),
                ('performer_type', models.CharField(blank=True, choices=[('group', 'Group'), ('solo', 'Solo')], db_comment='The performer type of the production.', help_text='Whether the performance is by a group or a solo artist. Accepted values: `group`, `solo`.', max_length=20)),
                ('media_gallery', models.ForeignKey(blank=True, db_comment='The media gallery of the production.', help_text='Media gallery associated with this production. `null` when not assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='media_library.mediagallery')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'db_table': 'production',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('position', models.PositiveIntegerField(db_comment='The position of the genre in the list of genres for the production.', help_text='Display order index for this genre within the production. Lower values appear first.')),
                ('genre', models.ForeignKey(db_comment='The genre of the production.', help_text='Genre being attached to the production.', on_delete=django.db.models.deletion.CASCADE, to='genres.genre')),
                ('production', models.ForeignKey(db_comment='The production that the genre belongs to.', help_text='Production the genre is attached to.', on_delete=django.db.models.deletion.CASCADE, to='productions.production')),
            ],
            options={
                'verbose_name': 'Production Genre',
                'verbose_name_plural': 'Production Genres',
                'db_table': 'production_genre',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='production',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Genres associated with this production, ordered by `ProductionGenre.position`.', related_name='productions', through='productions.ProductionGenre', to='genres.genre'),
        ),
        migrations.CreateModel(
            name='ProductionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('production', models.ForeignKey(db_comment='FK to Production.', help_text='Production the tag is attached to.', on_delete=django.db.models.deletion.CASCADE, to='productions.production')),
                ('tag', models.ForeignKey(db_comment='FK to Tag.', help_text='Tag being attached to the production.', on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'verbose_name': 'Production Tag',
                'verbose_name_plural': 'Production Tags',
                'db_table': 'production_tag',
                'ordering': ['tag__type', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='production',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this production.', related_name='productions', through='productions.ProductionTag', to='tags.tag'),
        ),
        migrations.CreateModel(
            name='ProductionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('supertitle', models.TextField(blank=True, db_comment='The supertitle of the production in the given language.', help_text='Short line displayed above the main title (e.g. a season label).', max_length=400)),
                ('title', models.TextField(blank=True, db_comment='The title of the production in the given language.', help_text='Main display title of the production in this language.', max_length=400)),
                ('artist_name', models.TextField(blank=True, db_comment='The name of the artist of the production in the given language.', help_text='Name of the performing artist or company in this language.', max_length=500)),
                ('tagline', models.TextField(blank=True, db_comment='The tagline of the production in the given language.', help_text='One-line marketing phrase for the production.', max_length=500)),
                ('teaser', models.TextField(blank=True, db_comment='The teaser of the production in the given language.', help_text='Short promotional text. May contain HTML — sanitise before saving.', max_length=500)),
                ('description', models.TextField(blank=True, db_comment='The description of the production in the given language.', help_text='Full-length description of the production. May contain HTML — sanitise before saving.', max_length=5000)),
                ('description_short', models.TextField(blank=True, db_comment='The short description of the production in the given language.', help_text='Condensed version of the description, suitable for cards and previews.', max_length=1000)),
                ('description_extra', models.TextField(blank=True, db_comment='The extra description of the production in the given language.', help_text='Supplementary description block (e.g. practical information).', max_length=2000)),
                ('description_2', models.TextField(blank=True, db_comment='The second description of the production in the given language.', help_text='Secondary description block for additional editorial content.', max_length=2000)),
                ('video_1', models.URLField(blank=True, db_comment='The URL of the first video of the production in the given language.', help_text='URL of the primary video (e.g. a Vimeo or YouTube embed URL).')),
                ('video_2', models.URLField(blank=True, db_comment='The URL of the second video of the production in the given language.', help_text='URL of the secondary video.')),
                ('meta_title', models.TextField(blank=True, db_comment='The meta title of the production in the given language.', help_text='SEO page title override. Falls back to `title` when empty.', max_length=500)),
                ('meta_description', models.TextField(blank=True, db_comment='The meta description of the production in the given language.', help_text='SEO meta description. Ideally 120–160 characters.', max_length=500)),
                ('language', models.ForeignKey(db_column='language_code', db_comment='The language of the translation.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='production_translations', to='languages.language')),
                ('production', models.ForeignKey(db_comment='The production that the translation belongs to.', help_text='Production this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='productions.production')),
            ],
            options={
                'verbose_name': 'Production Translation',
                'verbose_name_plural': 'Production Translations',
                'db_table': 'production_translation',
                'ordering': ['language__code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='production',
            name='uit_database_theme',
            field=models.ForeignKey(blank=True, db_comment='The theme of the production as defined in the UIT database.', help_text='UIT Database theme classification. `null` when not assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetheme'),
        ),
        migrations.AddField(
            model_name='production',
            name='uit_database_type',
            field=models.ForeignKey(blank=True, db_comment='The type of the production as defined in the UIT database.', help_text='UIT Database type classification. `null` when not assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetype'),
        ),
        migrations.AddConstraint(
            model_name='productiongenre',
            constraint=models.UniqueConstraint(fields=('production', 'genre'), name='unique_production_genre'),
        ),
        migrations.AddConstraint(
            model_name='productiontag',
            constraint=models.UniqueConstraint(fields=('production', 'tag'), name='unique_production_tag'),
        ),
        migrations.AddConstraint(
            model_name='productiontranslation',
            constraint=models.UniqueConstraint(fields=('production', 'language'), name='unique_production_language'),
        ),
    ]
