# Generated by Django 6.0.3 on 2026-03-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('description', models.TextField(blank=True, db_comment='The description of the production tag in the given language.', help_text='Multilingual description or context note for this tag within the production. May contain HTML - sanitise before saving.', max_length=1000)),
                ('language', models.ForeignKey(db_column='language_code', db_comment='The language of the translation.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='production_tag_translations', to='languages.language')),
                ('production_tag', models.ForeignKey(db_comment='FK to ProductionTag.', help_text='Production–tag link this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='productions.productiontag')),
            ],
            options={
                'verbose_name': 'Production Tag Translation',
                'verbose_name_plural': 'Production Tag Translations',
                'db_table': 'production_tag_translation',
                'ordering': ['language__code'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('production_tag', 'language'), name='unique_production_tag_language')],
            },
        ),
    ]
