# Generated by Django 6.0.2 on 2026-02-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '__first__'),
        ('productions', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
        migrations.AddField(
            model_name='production',
            name='tags',
            field=models.ManyToManyField(blank=True, db_comment='The tags of the production.', related_name='productions', through='productions.ProductionTag', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='productiontranslation',
            name='language',
            field=models.ForeignKey(db_column='language_code', db_comment='The language of the translation.', on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AddField(
            model_name='productiontranslation',
            name='production',
            field=models.ForeignKey(db_comment='The production that the translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='productions.production'),
        ),
        migrations.AddField(
            model_name='production',
            name='uit_database_theme',
            field=models.ForeignKey(blank=True, db_comment='The theme of the production as defined in the UIT database.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetheme'),
        ),
        migrations.AddField(
            model_name='production',
            name='uit_database_type',
            field=models.ForeignKey(blank=True, db_comment='The type of the production as defined in the UIT database.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetype'),
        ),
        migrations.AddConstraint(
            model_name='productiongenre',
            constraint=models.UniqueConstraint(fields=('production', 'genre'), name='unique_production_genre'),
        ),
        migrations.AddConstraint(
            model_name='productiontag',
            constraint=models.UniqueConstraint(fields=('production', 'tag'), name='unique_production_tag'),
        ),
        migrations.AddConstraint(
            model_name='productiontranslation',
            constraint=models.UniqueConstraint(fields=('production', 'language'), name='unique_production_language'),
        ),
    ]
