# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_merge_uitdatabank_theme_into_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.AlterModelOptions(
            name='productiongenre',
            options={'ordering': ['position', 'id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Production Genre', 'verbose_name_plural': 'Production Genres'},
        ),
        migrations.AlterModelOptions(
            name='productiontag',
            options={'ordering': ['tag__type', 'id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Production Tag', 'verbose_name_plural': 'Production Tags'},
        ),
        migrations.AlterModelOptions(
            name='productiontagtranslation',
            options={'ordering': ['language__code'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Production Tag Translation', 'verbose_name_plural': 'Production Tag Translations'},
        ),
        migrations.AlterModelOptions(
            name='productiontranslation',
            options={'ordering': ['language__code'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Production Translation', 'verbose_name_plural': 'Production Translations'},
        ),
        migrations.AlterModelOptions(
            name='uitdatabasetype',
            options={'ordering': ['name'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'UIT Database Type', 'verbose_name_plural': 'UIT Database Types'},
        ),
    ]
