# Generated by Django 6.0.2 on 2026-03-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_alter_genre_options_alter_genretranslation_options_and_more'),
        ('languages', '0005_alter_language_code_alter_language_is_active_and_more'),
        ('media_library', '0003_alter_mediagallery_options_and_more'),
        ('productions', '0004_alter_production_options_and_more'),
        ('tags', '0005_alter_tag_options_alter_tagtranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-id'], 'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.AlterModelOptions(
            name='productiongenre',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Production Genre', 'verbose_name_plural': 'Production Genres'},
        ),
        migrations.AlterModelOptions(
            name='productiontag',
            options={'ordering': ['tag__type', 'id'], 'verbose_name': 'Production Tag', 'verbose_name_plural': 'Production Tags'},
        ),
        migrations.AlterModelOptions(
            name='productiontranslation',
            options={'ordering': ['language__code'], 'verbose_name': 'Production Translation', 'verbose_name_plural': 'Production Translations'},
        ),
        migrations.AlterModelOptions(
            name='uitdatabasetheme',
            options={'ordering': ['name'], 'verbose_name': 'UIT Database Theme', 'verbose_name_plural': 'UIT Database Themes'},
        ),
        migrations.AlterModelOptions(
            name='uitdatabasetype',
            options={'ordering': ['name'], 'verbose_name': 'UIT Database Type', 'verbose_name_plural': 'UIT Database Types'},
        ),
        migrations.AlterField(
            model_name='production',
            name='attendance_mode',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], db_comment='The attendance mode of the production.', help_text='How the audience attends the production. Accepted values: `offline`, `online`.', max_length=20),
        ),
        migrations.AlterField(
            model_name='production',
            name='genres',
            field=models.ManyToManyField(blank=True, db_comment='The genres of the production.', help_text='Genres associated with this production, ordered by `ProductionGenre.position`.', related_name='productions', through='productions.ProductionGenre', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='production',
            name='media_gallery',
            field=models.ForeignKey(blank=True, db_comment='The media gallery of the production.', help_text='Media gallery associated with this production. `null` when not assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='media_library.mediagallery'),
        ),
        migrations.AlterField(
            model_name='production',
            name='performer_type',
            field=models.CharField(blank=True, choices=[('group', 'Group'), ('solo', 'Solo')], db_comment='The performer type of the production.', help_text='Whether the performance is by a group or a solo artist. Accepted values: `group`, `solo`.', max_length=20),
        ),
        migrations.AlterField(
            model_name='production',
            name='tags',
            field=models.ManyToManyField(blank=True, db_comment='The tags of the production.', help_text='Tags associated with this production.', related_name='productions', through='productions.ProductionTag', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='production',
            name='uit_database_theme',
            field=models.ForeignKey(blank=True, db_comment='The theme of the production as defined in the UIT database.', help_text='UIT Database theme classification. `null` when not assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetheme'),
        ),
        migrations.AlterField(
            model_name='production',
            name='uit_database_type',
            field=models.ForeignKey(blank=True, db_comment='The type of the production as defined in the UIT database.', help_text='UIT Database type classification. `null` when not assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetype'),
        ),
        migrations.AlterField(
            model_name='productiongenre',
            name='genre',
            field=models.ForeignKey(db_comment='The genre of the production.', help_text='Genre being attached to the production.', on_delete=django.db.models.deletion.CASCADE, to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='productiongenre',
            name='position',
            field=models.PositiveIntegerField(db_comment='The position of the genre in the list of genres for the production.', help_text='Display order index for this genre within the production. Lower values appear first.'),
        ),
        migrations.AlterField(
            model_name='productiongenre',
            name='production',
            field=models.ForeignKey(db_comment='The production that the genre belongs to.', help_text='Production the genre is attached to.', on_delete=django.db.models.deletion.CASCADE, to='productions.production'),
        ),
        migrations.AlterField(
            model_name='productiontag',
            name='production',
            field=models.ForeignKey(db_comment='FK to Production.', help_text='Production the tag is attached to.', on_delete=django.db.models.deletion.CASCADE, to='productions.production'),
        ),
        migrations.AlterField(
            model_name='productiontag',
            name='tag',
            field=models.ForeignKey(db_comment='FK to Tag.', help_text='Tag being attached to the production.', on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='artist_name',
            field=models.CharField(blank=True, db_comment='The name of the artist of the production in the given language.', help_text='Name of the performing artist or company in this language.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description',
            field=models.TextField(blank=True, db_comment='The description of the production in the given language.', help_text='Full-length description of the production. May contain HTML — sanitise before saving.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_2',
            field=models.TextField(blank=True, db_comment='The second description of the production in the given language.', help_text='Secondary description block for additional editorial content.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_extra',
            field=models.TextField(blank=True, db_comment='The extra description of the production in the given language.', help_text='Supplementary description block (e.g. practical information).'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_short',
            field=models.TextField(blank=True, db_comment='The short description of the production in the given language.', help_text='Condensed version of the description, suitable for cards and previews.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='language',
            field=models.ForeignKey(db_column='language_code', db_comment='The language of the translation.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='production_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='meta_description',
            field=models.TextField(blank=True, db_comment='The meta description of the production in the given language.', help_text='SEO meta description. Ideally 120–160 characters.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='meta_title',
            field=models.CharField(blank=True, db_comment='The meta title of the production in the given language.', help_text='SEO page title override. Falls back to `title` when empty.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='production',
            field=models.ForeignKey(db_comment='The production that the translation belongs to.', help_text='Production this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='productions.production'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='supertitle',
            field=models.CharField(blank=True, db_comment='The supertitle of the production in the given language.', help_text='Short line displayed above the main title (e.g. a season label).', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='tagline',
            field=models.CharField(blank=True, db_comment='The tagline of the production in the given language.', help_text='One-line marketing phrase for the production.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='teaser',
            field=models.TextField(blank=True, db_comment='The teaser of the production in the given language.', help_text='Short promotional text. May contain HTML — sanitise before saving.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='title',
            field=models.CharField(blank=True, db_comment='The title of the production in the given language.', help_text='Main display title of the production in this language.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='video_1',
            field=models.URLField(blank=True, db_comment='The URL of the first video of the production in the given language.', help_text='URL of the primary video (e.g. a Vimeo or YouTube embed URL).'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='video_2',
            field=models.URLField(blank=True, db_comment='The URL of the second video of the production in the given language.', help_text='URL of the secondary video.'),
        ),
        migrations.AlterField(
            model_name='uitdatabasetheme',
            name='name',
            field=models.CharField(db_comment='The name of the theme.', help_text='Human-readable name of the UIT Database theme (e.g. `Theater`, `Muziek`).', max_length=200),
        ),
        migrations.AlterField(
            model_name='uitdatabasetype',
            name='name',
            field=models.CharField(db_comment='The name of the type.', help_text='Human-readable name of the UIT Database type (e.g. `Voorstelling`, `Concert`).', max_length=200),
        ),
    ]
