# Generated by Django 6.0.2 on 2026-03-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0004_alter_genre_options_alter_genretranslation_options_and_more'),
        ('languages', '0006_alter_language_code_alter_language_is_active_and_more'),
        ('media_library', '0004_alter_mediagallery_options_and_more'),
        ('productions', '0005_alter_production_options_and_more'),
        ('tags', '0006_alter_tag_options_alter_tagtranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'Production', 'verbose_name_plural': 'Productions'},
        ),
        migrations.AlterModelOptions(
            name='productiongenre',
            options={'verbose_name': 'Production Genre', 'verbose_name_plural': 'Production Genres'},
        ),
        migrations.AlterModelOptions(
            name='productiontag',
            options={'verbose_name': 'Production Tag', 'verbose_name_plural': 'Production Tags'},
        ),
        migrations.AlterModelOptions(
            name='productiontranslation',
            options={'verbose_name': 'Production Translation', 'verbose_name_plural': 'Production Translations'},
        ),
        migrations.AlterModelOptions(
            name='uitdatabasetheme',
            options={'verbose_name': 'UIT Database Theme', 'verbose_name_plural': 'UIT Database Themes'},
        ),
        migrations.AlterModelOptions(
            name='uitdatabasetype',
            options={'verbose_name': 'UIT Database Type', 'verbose_name_plural': 'UIT Database Types'},
        ),
        migrations.AlterField(
            model_name='production',
            name='attendance_mode',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], db_comment='The attendance mode of the production.', max_length=20),
        ),
        migrations.AlterField(
            model_name='production',
            name='genres',
            field=models.ManyToManyField(blank=True, db_comment='The genres of the production.', related_name='productions', through='productions.ProductionGenre', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='production',
            name='media_gallery',
            field=models.ForeignKey(blank=True, db_comment='The media gallery of the production.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='media_library.mediagallery'),
        ),
        migrations.AlterField(
            model_name='production',
            name='performer_type',
            field=models.CharField(blank=True, choices=[('group', 'Group'), ('solo', 'Solo')], db_comment='The performer type of the production.', max_length=20),
        ),
        migrations.AlterField(
            model_name='production',
            name='tags',
            field=models.ManyToManyField(blank=True, db_comment='The tags of the production.', related_name='productions', through='productions.ProductionTag', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='production',
            name='uit_database_theme',
            field=models.ForeignKey(blank=True, db_comment='The theme of the production as defined in the UIT database.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetheme'),
        ),
        migrations.AlterField(
            model_name='production',
            name='uit_database_type',
            field=models.ForeignKey(blank=True, db_comment='The type of the production as defined in the UIT database.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='productions.uitdatabasetype'),
        ),
        migrations.AlterField(
            model_name='productiongenre',
            name='genre',
            field=models.ForeignKey(db_comment='The genre of the production.', on_delete=django.db.models.deletion.CASCADE, to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='productiongenre',
            name='position',
            field=models.PositiveIntegerField(db_comment='The position of the genre in the list of genres for the production.'),
        ),
        migrations.AlterField(
            model_name='productiongenre',
            name='production',
            field=models.ForeignKey(db_comment='The production that the genre belongs to.', on_delete=django.db.models.deletion.CASCADE, to='productions.production'),
        ),
        migrations.AlterField(
            model_name='productiontag',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productions.production'),
        ),
        migrations.AlterField(
            model_name='productiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='artist_name',
            field=models.CharField(blank=True, db_comment='The name of the artist of the production in the given language.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description',
            field=models.TextField(blank=True, db_comment='The description of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_2',
            field=models.TextField(blank=True, db_comment='The second description of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_extra',
            field=models.TextField(blank=True, db_comment='The extra description of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_short',
            field=models.TextField(blank=True, db_comment='The short description of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='language',
            field=models.ForeignKey(db_column='language_code', db_comment='The language of the translation.', on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='meta_description',
            field=models.TextField(blank=True, db_comment='The meta description of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='meta_title',
            field=models.CharField(blank=True, db_comment='The meta title of the production in the given language.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='production',
            field=models.ForeignKey(db_comment='The production that the translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='productions.production'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='supertitle',
            field=models.CharField(blank=True, db_comment='The supertitle of the production in the given language.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='tagline',
            field=models.CharField(blank=True, db_comment='The tagline of the production in the given language.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='teaser',
            field=models.TextField(blank=True, db_comment='The teaser of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='title',
            field=models.CharField(blank=True, db_comment='The title of the production in the given language.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='video_1',
            field=models.URLField(blank=True, db_comment='The URL of the first video of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='video_2',
            field=models.URLField(blank=True, db_comment='The URL of the second video of the production in the given language.'),
        ),
        migrations.AlterField(
            model_name='uitdatabasetheme',
            name='name',
            field=models.CharField(db_comment='The name of the theme.', max_length=200),
        ),
        migrations.AlterField(
            model_name='uitdatabasetype',
            name='name',
            field=models.CharField(db_comment='The name of the type.', max_length=200),
        ),
    ]
