# Generated by Django 6.0.2 on 2026-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0007_alter_production_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='productiongenre',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='productiontag',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='productiontranslation',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='uitdatabasetheme',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='uitdatabasetype',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
    ]
