# Generated by Django 6.0.2 on 2026-03-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0007_genre_vendor_id'),
        ('productions', '0008_production_external_id_productiongenre_external_id_and_more'),
        ('tags', '0008_tag_external_id_tagtranslation_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Genres associated with this production, ordered by `ProductionGenre.position`.', related_name='productions', through='productions.ProductionGenre', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='production',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this production.', related_name='productions', through='productions.ProductionTag', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='artist_name',
            field=models.TextField(blank=True, db_comment='The name of the artist of the production in the given language.', help_text='Name of the performing artist or company in this language.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description',
            field=models.TextField(blank=True, db_comment='The description of the production in the given language.', help_text='Full-length description of the production. May contain HTML — sanitise before saving.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_2',
            field=models.TextField(blank=True, db_comment='The second description of the production in the given language.', help_text='Secondary description block for additional editorial content.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_extra',
            field=models.TextField(blank=True, db_comment='The extra description of the production in the given language.', help_text='Supplementary description block (e.g. practical information).', max_length=2000),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='description_short',
            field=models.TextField(blank=True, db_comment='The short description of the production in the given language.', help_text='Condensed version of the description, suitable for cards and previews.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='meta_description',
            field=models.TextField(blank=True, db_comment='The meta description of the production in the given language.', help_text='SEO meta description. Ideally 120–160 characters.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='meta_title',
            field=models.TextField(blank=True, db_comment='The meta title of the production in the given language.', help_text='SEO page title override. Falls back to `title` when empty.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='supertitle',
            field=models.TextField(blank=True, db_comment='The supertitle of the production in the given language.', help_text='Short line displayed above the main title (e.g. a season label).', max_length=400),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='tagline',
            field=models.TextField(blank=True, db_comment='The tagline of the production in the given language.', help_text='One-line marketing phrase for the production.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='teaser',
            field=models.TextField(blank=True, db_comment='The teaser of the production in the given language.', help_text='Short promotional text. May contain HTML — sanitise before saving.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='title',
            field=models.TextField(blank=True, db_comment='The title of the production in the given language.', help_text='Main display title of the production in this language.', max_length=400),
        ),
    ]
