# Generated by Django 6.0.3 on 2026-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0009_alter_production_genres_alter_production_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontranslation',
            name='description',
            field=models.TextField(blank=True, db_comment='The description of the production in the given language.', help_text='Full-length description of the production. May contain HTML - sanitise before saving.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='productiontranslation',
            name='teaser',
            field=models.TextField(blank=True, db_comment='The teaser of the production in the given language.', help_text='Short promotional text. May contain HTML - sanitise before saving.', max_length=500),
        ),
    ]
