# Generated by Django 6.0.3 on 2026-04-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('street', models.CharField(blank=True, db_comment='Street name of the location.', help_text='Street name of the location.', max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_comment='Street number of the location.', help_text='Street / house number.', max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, db_comment='Postal code of the location.', help_text='Postal or ZIP code.', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_comment='City of the location.', help_text='City in which the location sits.', max_length=100, null=True)),
                ('country', models.CharField(db_comment='Country of the location.', default='BE', help_text='Country in which the location sits.', max_length=100)),
                ('phone_1', models.CharField(blank=True, db_comment='Primary phone number.', help_text='Primary contact phone number (optional).', max_length=50, null=True)),
                ('phone_2', models.CharField(blank=True, db_comment='Secondary phone number.', help_text='Secondary contact phone number (optional).', max_length=50, null=True)),
                ('is_own_location', models.BooleanField(db_comment='Whether this is an owned/operated location.', default=False, help_text='``True`` when this venue is owned or operated by the organisation.')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('location', models.ForeignKey(db_comment='FK to Location.', help_text='Parent location this space belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='locations.location')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'db_table': 'space',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('seat_selection', models.BooleanField(db_comment='Whether seat selection is available.', default=False, help_text='``True`` when visitors can choose a specific seat during purchase.')),
                ('open_seating', models.BooleanField(db_comment='Whether seating is open / general admission.', default=False, help_text='``True`` when seating is general-admission (no fixed seat assignment).')),
                ('space', models.ForeignKey(blank=True, db_comment='FK to Space.', help_text='Parent space this hall belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='locations.space')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'db_table': 'hall',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HallTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='Translated name of the hall.', help_text='Localised display name of the hall.', max_length=255)),
                ('remark', models.TextField(blank=True, db_comment='Optional translated remark about the hall.', help_text='Optional localised note about the hall (e.g. accessibility information).', null=True)),
                ('hall', models.ForeignKey(db_comment='FK to Hall.', help_text='Hall this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.hall')),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='hall_translations', to='languages.language')),
            ],
            options={
                'verbose_name': 'Hall Translation',
                'verbose_name_plural': 'Hall Translations',
                'db_table': 'hall_translation',
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('hall', 'language'), name='unique_hall_language')],
            },
        ),
        migrations.CreateModel(
            name='LocationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='Translated name of the location.', help_text='Localised display name of the location.', max_length=255)),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='location_translations', to='languages.language')),
                ('location', models.ForeignKey(db_comment='FK to Location.', help_text='Location this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.location')),
            ],
            options={
                'verbose_name': 'Location Translation',
                'verbose_name_plural': 'Location Translations',
                'db_table': 'location_translation',
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('location', 'language'), name='unique_location_language')],
            },
        ),
        migrations.CreateModel(
            name='SpaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='Translated name of the space.', help_text='Localised display name of the space.', max_length=255)),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='space_translations', to='languages.language')),
                ('space', models.ForeignKey(db_comment='FK to Space.', help_text='Space this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.space')),
            ],
            options={
                'verbose_name': 'Space Translation',
                'verbose_name_plural': 'Space Translations',
                'db_table': 'space_translation',
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('space', 'language'), name='unique_space_language')],
            },
        ),
    ]
