# Generated by Django 6.0.2 on 2026-03-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_language_code_alter_language_is_active_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Hall', 'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='halltranslation',
            options={'verbose_name': 'Hall Translation', 'verbose_name_plural': 'Hall Translations'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationtranslation',
            options={'verbose_name': 'Location Translation', 'verbose_name_plural': 'Location Translations'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AlterModelOptions(
            name='spacetranslation',
            options={'verbose_name': 'Space Translation', 'verbose_name_plural': 'Space Translations'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='open_seating',
            field=models.BooleanField(db_comment='Whether seating is open/general admission', default=False),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seat_selection',
            field=models.BooleanField(db_comment='Whether seat selection is available', default=False),
        ),
        migrations.AlterField(
            model_name='hall',
            name='space',
            field=models.ForeignKey(db_comment='Reference to the space where the hall is located', on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='locations.space'),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='hall',
            field=models.ForeignKey(db_comment='Reference to the hall', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.hall'),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='language',
            field=models.ForeignKey(db_comment='Language of the translation', on_delete=django.db.models.deletion.CASCADE, related_name='hall_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='name',
            field=models.CharField(db_comment='Translated name of the hall', max_length=255),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='remark',
            field=models.TextField(blank=True, db_comment='Optional remark about the hall', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(db_comment='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(db_comment='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_own_location',
            field=models.BooleanField(db_comment='Whether this is an owned location or not', default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.CharField(db_comment='The street number of the location.', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_1',
            field=models.CharField(blank=True, db_comment='Primary phone number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_2',
            field=models.CharField(blank=True, db_comment='Secondary phone number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(db_comment='The postal code of the location.', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(db_comment='The street of the location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='language',
            field=models.ForeignKey(db_comment='Language of the translation', on_delete=django.db.models.deletion.CASCADE, related_name='location_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='location',
            field=models.ForeignKey(db_comment='Reference to the location', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='name',
            field=models.CharField(db_comment='Translated name of the location', max_length=255),
        ),
        migrations.AlterField(
            model_name='space',
            name='location',
            field=models.ForeignKey(db_comment='Reference to the location of the space', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='spacetranslation',
            name='language',
            field=models.ForeignKey(db_comment='Language of the translation', on_delete=django.db.models.deletion.CASCADE, related_name='space_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='spacetranslation',
            name='name',
            field=models.CharField(db_comment='Translated name of the space', max_length=255),
        ),
        migrations.AlterField(
            model_name='spacetranslation',
            name='space',
            field=models.ForeignKey(db_comment='Reference to the space', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.space'),
        ),
    ]
