# Generated by Django 6.0.2 on 2026-03-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_alter_language_code_alter_language_is_active_and_more'),
        ('locations', '0004_alter_hall_options_alter_halltranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['id'], 'verbose_name': 'Hall', 'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='halltranslation',
            options={'ordering': ['id'], 'verbose_name': 'Hall Translation', 'verbose_name_plural': 'Hall Translations'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationtranslation',
            options={'ordering': ['id'], 'verbose_name': 'Location Translation', 'verbose_name_plural': 'Location Translations'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['id'], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AlterModelOptions(
            name='spacetranslation',
            options={'ordering': ['id'], 'verbose_name': 'Space Translation', 'verbose_name_plural': 'Space Translations'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='open_seating',
            field=models.BooleanField(db_comment='Whether seating is open / general admission.', default=False, help_text='``True`` when seating is general-admission (no fixed seat assignment).'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seat_selection',
            field=models.BooleanField(db_comment='Whether seat selection is available.', default=False, help_text='``True`` when visitors can choose a specific seat during purchase.'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='space',
            field=models.ForeignKey(db_comment='FK to Space.', help_text='Parent space this hall belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='locations.space'),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='hall',
            field=models.ForeignKey(db_comment='FK to Hall.', help_text='Hall this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.hall'),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='language',
            field=models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='hall_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='name',
            field=models.CharField(db_comment='Translated name of the hall.', help_text='Localised display name of the hall.', max_length=255),
        ),
        migrations.AlterField(
            model_name='halltranslation',
            name='remark',
            field=models.TextField(blank=True, db_comment='Optional translated remark about the hall.', help_text='Optional localised note about the hall (e.g. accessibility information).', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(db_comment='City of the location.', help_text='City in which the location sits.', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(db_comment='Country of the location.', help_text='Country in which the location sits.', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_own_location',
            field=models.BooleanField(db_comment='Whether this is an owned/operated location.', default=False, help_text='``True`` when this venue is owned or operated by the organisation.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.CharField(db_comment='Street number of the location.', help_text='Street / house number.', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_1',
            field=models.CharField(blank=True, db_comment='Primary phone number.', help_text='Primary contact phone number (optional).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_2',
            field=models.CharField(blank=True, db_comment='Secondary phone number.', help_text='Secondary contact phone number (optional).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(db_comment='Postal code of the location.', help_text='Postal or ZIP code.', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(db_comment='Street name of the location.', help_text='Street name of the location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='language',
            field=models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='location_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='location',
            field=models.ForeignKey(db_comment='FK to Location.', help_text='Location this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='name',
            field=models.CharField(db_comment='Translated name of the location.', help_text='Localised display name of the location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='space',
            name='location',
            field=models.ForeignKey(db_comment='FK to Location.', help_text='Parent location this space belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='spacetranslation',
            name='language',
            field=models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='space_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='spacetranslation',
            name='name',
            field=models.CharField(db_comment='Translated name of the space.', help_text='Localised display name of the space.', max_length=255),
        ),
        migrations.AlterField(
            model_name='spacetranslation',
            name='space',
            field=models.ForeignKey(db_comment='FK to Space.', help_text='Space this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locations.space'),
        ),
    ]
