# Generated by Django 6.0.2 on 2026-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_hall_options_alter_halltranslation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='halltranslation',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='locationtranslation',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
        migrations.AddField(
            model_name='spacetranslation',
            name='external_id',
            field=models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True),
        ),
    ]
