# Generated by Django 6.0.2 on 2026-03-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_hall_external_id_halltranslation_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='space',
            field=models.ForeignKey(blank=True, db_comment='FK to Space.', help_text='Parent space this hall belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='locations.space'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, db_comment='City of the location.', help_text='City in which the location sits.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(db_comment='Country of the location.', default='BE', help_text='Country in which the location sits.', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.CharField(blank=True, db_comment='Street number of the location.', help_text='Street / house number.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, db_comment='Postal code of the location.', help_text='Postal or ZIP code.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, db_comment='Street name of the location.', help_text='Street name of the location.', max_length=255, null=True),
        ),
    ]
