# Generated by Django 6.0.3 on 2026-03-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('code', models.CharField(db_comment='ISO 639-1 code - primary key.', help_text='ISO 639-1 two-letter code (e.g. `en`, `nl`, `fr`).', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Display name of the language.', help_text='Human-readable English name of the language (e.g. `English`, `Dutch`).', max_length=15)),
                ('is_active', models.BooleanField(db_comment='Whether the language is publicly active.', default=False, help_text='Controls whether this language is visible in consumer-facing interfaces. Set to `false` while translations are still being prepared.')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
    ]
