# Generated by Django 6.0.2 on 2026-02-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
    ]
