# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
    ]
