# Generated by Django 6.0.2 on 2026-03-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_alter_language_code_alter_language_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(db_comment='The ISO 639-1 code of the language ex. en, nl, etc.', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(db_comment='Wether the language should be shown in the frontend or not. Useful for when a language is still being implemented.', default=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_comment='The name of the language ex. English, Dutch, etc.', max_length=15),
        ),
    ]
