# Generated by Django 6.0.2 on 2026-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_alter_language_code_alter_language_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(db_comment='ISO 639-1 code — primary key.', help_text='ISO 639-1 two-letter code (e.g. `en`, `nl`, `fr`).', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(db_comment='Whether the language is publicly active.', default=False, help_text='Controls whether this language is visible in consumer-facing interfaces. Set to `false` while translations are still being prepared.'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_comment='Display name of the language.', help_text='Human-readable English name of the language (e.g. `English`, `Dutch`).', max_length=15),
        ),
    ]
