# Generated by Django 6.0.3 on 2026-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_language_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(db_comment='ISO 639-1 code - primary key.', help_text='ISO 639-1 two-letter code (e.g. `en`, `nl`, `fr`).', max_length=2, primary_key=True, serialize=False),
        ),
    ]
