# Generated by Django 6.0.3 on 2026-03-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('vendor_id', models.CharField(blank=True, db_comment='Vendor identifier for the genre.', help_text='Vendor-specific identifier from the upstream API.', max_length=255, null=True)),
                ('type', models.CharField(db_comment='Technical type of the genre.', help_text="Internal snake_case identifier (e.g. 'theater', 'festival').", max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genre',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenreUseAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='Use-case label for the genre.', help_text="Context in which genres with this role are applied (e.g. 'genre', 'tag').", max_length=50)),
            ],
            options={
                'verbose_name': 'Genre Use As',
                'verbose_name_plural': 'Genres Used As',
                'db_table': 'genre_use_as',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenreTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_comment='External identifier from the viernulvier database.', help_text='Optional external identifier for integration with the viernulvier database.', null=True)),
                ('name', models.CharField(db_comment='Translated name of the genre.', help_text='Localised display name of the genre.', max_length=50)),
                ('genre', models.ForeignKey(db_comment='FK to Genre.', help_text='Genre this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='genres.genre')),
                ('language', models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='genre_translations', to='languages.language')),
            ],
            options={
                'verbose_name': 'Genre Translation',
                'verbose_name_plural': 'Genre Translations',
                'db_table': 'genre_translation',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='genre',
            name='use_as',
            field=models.ForeignKey(db_comment='FK to GenreUseAs.', help_text='Defines how this genre is applied (taxonomy or tagging).', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='genres.genreuseas'),
        ),
    ]
