# Generated by Django 6.0.2 on 2026-03-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('languages', '0004_alter_language_code_alter_language_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='genretranslation',
            options={'verbose_name': 'Genre Translation', 'verbose_name_plural': 'Genre Translations'},
        ),
        migrations.AlterModelOptions(
            name='genreuseas',
            options={'verbose_name': 'Genre Use As', 'verbose_name_plural': 'Genres Used As'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(db_comment="The type of the genre ex. 'Theater', 'Festival', 'Boek voorstelling', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='use_as',
            field=models.ForeignKey(db_comment='Reference to GenreUseAs.', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='genres.genreuseas'),
        ),
        migrations.AlterField(
            model_name='genretranslation',
            name='genre',
            field=models.ForeignKey(db_comment='Reference to the genre.', on_delete=django.db.models.deletion.CASCADE, related_name='genre_translations', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='genretranslation',
            name='language',
            field=models.ForeignKey(db_comment='Reference to the language of the genre translation.', on_delete=django.db.models.deletion.CASCADE, related_name='genre_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='genretranslation',
            name='name',
            field=models.CharField(db_comment='The name of the genre in a specific language', max_length=50),
        ),
        migrations.AlterField(
            model_name='genreuseas',
            name='name',
            field=models.CharField(db_comment="Use cases for the genre, ex. 'tag', 'genre'", max_length=50),
        ),
    ]
