# Generated by Django 6.0.2 on 2026-03-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_options_alter_genretranslation_options_and_more'),
        ('languages', '0005_alter_language_code_alter_language_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='genretranslation',
            options={'ordering': ['id'], 'verbose_name': 'Genre Translation', 'verbose_name_plural': 'Genre Translations'},
        ),
        migrations.AlterModelOptions(
            name='genreuseas',
            options={'ordering': ['id'], 'verbose_name': 'Genre Use As', 'verbose_name_plural': 'Genres Used As'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(db_comment='Technical type of the genre.', help_text="Internal snake_case identifier (e.g. 'theater', 'festival').", max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='use_as',
            field=models.ForeignKey(db_comment='FK to GenreUseAs.', help_text='Defines how this genre is applied (taxonomy or tagging).', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='genres.genreuseas'),
        ),
        migrations.AlterField(
            model_name='genretranslation',
            name='genre',
            field=models.ForeignKey(db_comment='FK to Genre.', help_text='Genre this translation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='genretranslation',
            name='language',
            field=models.ForeignKey(db_comment='FK to Language.', help_text='Language of this translation.', on_delete=django.db.models.deletion.CASCADE, related_name='genre_translations', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='genretranslation',
            name='name',
            field=models.CharField(db_comment='Translated name of the genre.', help_text='Localised display name of the genre.', max_length=50),
        ),
        migrations.AlterField(
            model_name='genreuseas',
            name='name',
            field=models.CharField(db_comment='Use-case label for the genre.', help_text="Context in which genres with this role are applied (e.g. 'genre', 'tag').", max_length=50),
        ),
    ]
