# Generated by Django 6.0.5 on 2026-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_remove_genre_use_as'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='genretranslation',
            options={'ordering': ['id'], 'permissions': [('can_export', 'Can export data via admin')], 'verbose_name': 'Genre Translation', 'verbose_name_plural': 'Genre Translations'},
        ),
    ]
