# Generated by Django 6.0.2 on 2026-03-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0006_genre_external_id_genretranslation_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='vendor_id',
            field=models.CharField(blank=True, db_comment='Vendor identifier for the genre.', help_text='Vendor-specific identifier from the upstream API.', max_length=255, null=True),
        ),
    ]
